services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=scholarshipfinder
      - POSTGRES_PASSWORD=scholarshipfinder
      - POSTGRES_DB=scholarshipfinder
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    image: chromadb/chroma
    volumes:
      - chroma_data:/data
    ports:
      - "5010:8000"

volumes:
  pg_data:
  chroma_data: