# Generated by Django 5.2.1 on 2025-05-20 20:25

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "education_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "field_of_study",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gpa", models.FloatField(blank=True, null=True)),
                (
                    "target_degree",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sat_score", models.PositiveIntegerField(blank=True, null=True)),
                ("act_score", models.PositiveIntegerField(blank=True, null=True)),
                ("gre_score", models.PositiveIntegerField(blank=True, null=True)),
                ("other_test", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "institution",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("ethnicity", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "citizenship",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "income_bracket",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "first_generation",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "has_disability",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "military_affiliation",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("special_circumstances", models.TextField(blank=True, null=True)),
                ("career_goals", models.TextField(blank=True, null=True)),
                (
                    "extracurricular_activities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User preferences in JSON format",
                        null=True,
                    ),
                ),
                ("volunteer_experience", models.TextField(blank=True, null=True)),
                (
                    "special_talents",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "preferred_location",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User preferred study locatoin in JSON format",
                        null=True,
                    ),
                ),
                (
                    "study_format",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "willing_to_relocate",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "scholarship_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Multiple scholarship types selected by users",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
