# Generated by Django 5.2.1 on 2025-05-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="extracurricular_activities",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="User preferences in JSON format",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_generation",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="has_disability",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="military_affiliation",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="scholarship_types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Multiple scholarship types selected by users",
                null=True,
            ),
        ),
    ]
