# Generated by Django 5.2.1 on 2025-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_profile_extracurricular_activities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="preferred_location",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="User preferred study locatoin in JSON format",
                null=True,
            ),
        ),
    ]
