# Generated by Django 5.2.1 on 2025-05-18 04:48

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("full", "Full"), ("partial", "Partial")],
                        max_length=100,
                    ),
                ),
                (
                    "degree_level",
                    models.CharField(
                        choices=[("bachelor", "Bachelor"), ("master", "Master")],
                        max_length=100,
                    ),
                ),
                ("end_date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
