# Generated by Django 5.2.1 on 2025-05-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="registration_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
