# Generated by Django 5.2.1 on 2025-05-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0002_alter_scholarship_deadline_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scholarship",
            old_name="url",
            new_name="official_url",
        ),
        migrations.AddField(
            model_name="scholarship",
            name="source_url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
