# Generated by Django 5.2.1 on 2025-05-19 17:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scholarships",
            "0004_scholarship_must_relocate_scholarship_study_format_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="scholarship",
            name="degree",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), size=None
            ),
        ),
    ]
